kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-run
rules:
  - verbs:
      - get
      - watch
      - list
      - create
    apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
  - verbs:
      - get
      - watch
      - list
      - exec
    apiGroups:
      - tekton.dev
    resources:
      - pipelines
