apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: create-bm4-cluster-assets
  namespace: hpe-redhat
spec:
  tasks:
    - name: oneview-create-asset
      params:
        - name: templateName
          value: Openshift-BM2-v4
        - name: serialNumber
          value: cz250300vk
        - name: serverName
          value: ocp-bm4-master01
      runAfter:
        - clean-pxe-cluster
      taskRef:
        kind: Task
        name: oneview-create-asset
    - name: oneview-create-asset-oxn
      params:
        - name: templateName
          value: Openshift-BM2-v4
        - name: serialNumber
          value: cz250300vd
        - name: serverName
          value: ocp-bm4-master02
      runAfter:
        - clean-pxe-cluster
      taskRef:
        kind: Task
        name: oneview-create-asset
    - name: oneview-create-asset-s1n
      params:
        - name: templateName
          value: Openshift-BM2-v4
        - name: serialNumber
          value: cz250300v1
        - name: serverName
          value: ocp-bm4-master03
      runAfter:
        - clean-pxe-cluster
      taskRef:
        kind: Task
        name: oneview-create-asset
    - name: clean-pxe-cluster
      params:
        - name: cluster
          value: bm4
      taskRef:
        kind: Task
        name: clean-pxe-cluster
    - name: oneview-info-asset
      params:
        - name: serverName
          value: ocp-bm4-master01
        - name: namespace
          value: bm4
      runAfter:
        - oneview-create-asset
      taskRef:
        kind: Task
        name: oneview-register-asset
      workspaces:
        - name: result
          workspace: result
    - name: oneview-info-asset-55p
      params:
        - name: serverName
          value: ocp-bm4-master03
        - name: namespace
          value: bm4
      runAfter:
        - oneview-create-asset-s1n
      taskRef:
        kind: Task
        name: oneview-register-asset
      workspaces:
        - name: result
          workspace: result
    - name: oneview-info-asset-phg
      params:
        - name: serverName
          value: ocp-bm4-master02
        - name: namespace
          value: bm4
      runAfter:
        - oneview-create-asset-oxn
      taskRef:
        kind: Task
        name: oneview-register-asset
      workspaces:
        - name: result
          workspace: result
  workspaces:
    - name: result
