kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-run-hpe-redhat
  namespace: hpe-redhat
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: hpe_redhat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-run
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: update-agents-baremetal-hpe-redhat
  namespace: baremetal
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: hpe-redhat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: update-agents-baremetal
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reset-metal3-hpe-redhat
  namespace: openshift-machine-api
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: hpe_redhat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reset-metal3
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-bmh-bm4
  namespace: bm4
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: hpe-redhat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit-bmh
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-bmh-bm4-user
  namespace: bm4
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: hpe_redhat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit-bmh
